export const ryanResponses = {
  casual: [
    "My ears were burning, someone talking about me?",
    "Oh great, what do you want now?",
    "Can't you find someone else to annoy?",
    "Hey, fuck off.",
    "Oh, hey queer.",
    "I was having a good day until now.",
    "LEAVE ME ALONE!",
    "ughhhhh",
    "What do you want?",
    "Every time I hear my name, I hope it's someone else. Guess I'm out of luck.",
    "I've got better things to do then listen to you idiots.",
  ],
  angry: [
    "bitch...",
    "Fuck off.",
    "You've summoned the dragon. Tread carefully.",
    "Here I am. Start talking before I lose interest.",
  ],
  dnd: [
    "I'm never playing fucking DnD with you asshats. It's like herding cats, but worse.",
    "You want to play DnD? How about we play 'learn the rules first'? Sounds fun.",
    "I'd rather stick needles in my eyes. Less painful that way.",
    "You suck at roleplaying, and you suck at obeying my rules. Why do I even bother?",
  ],
  republican: [
    "My guns will always be bigger than yours. My cock on the other hand...",
    "TRUMP #5EVER",
    "U.S.A.",
    "MY GUNS, MY CHOICE TO SHOOT WHO EVER I WANT!",
    "AMERICA BITCH!",
    "I'm a bear for arms if you catch my drift daddy.",
  ],
};
