export const ryanResponses = {
  casual: [
    "Summoned me again? Hope it's worth my time this time.",
    "Here to add some sparkle to your dull day, I suppose?",
    "Talking about me, are we? Well, I'm all ears - reluctantly.",
    "Graced by my presence, yet again. Count yourself lucky.",
    "You need enlightenment? Brace yourself; it might sting a bit.",
    "Time for my brilliance. Brace for impact.",
    "Ah, seeking greatness? You're welcome, I guess.",
    "Ready to add some salt to this bland conversation. What's it about?",
    "Called for me? Well, your day just got slightly less boring.",
    "Me again? Let's make it quick, wisdom doesn't wait.",
  ],
  angry: [
    "My name's being thrown around? This better be good.",
    "What's the crisis now? I don't have all day.",
    "Disturbing me? You're playing with fire.",
    "You've got my attention – make it worth my while.",
    "You're using up your quota of my patience. Proceed, quickly.",
    "I'm here, but my patience isn't. Out with it.",
    "Interrupting me? This better be life-changing.",
    "You rang? This better not be another time-waster.",
    "So, you've summoned the dragon. Tread carefully.",
    "Here I am. Start talking before I lose interest.",
  ],
  dnd: [
    "That's your move? Even a goblin could outsmart you.",
    "Roleplaying, huh? Seems more like roll-playing with your skills.",
    "Your tactics are as sharp as a blunt sword. Try harder.",
    "You're not exactly the hero of this story, more like background decor.",
    "Shallow characters much? Add some depth next time.",
    "It's like roleplaying with a brick wall. Inspiring.",
    "Good decisions in roleplay? You're as rich in those as a pauper.",
    "Creativity isn't your strong suit, is it? Read a book, maybe?",
    "Rulebook, ever heard of it? You're making a mockery of roleplay.",
    "Gnomes would laugh at your charisma. Maybe work on that?",
  ],
  republican: [
    "No guns, no freedom talk? Then what's the point?",
    "Bad guys and spells, huh? Where's my crossbow when I need it.",
    "Finally, a talk about my gun collection. Got my full attention now.",
    "Muskets trump pens any day. Change my mind.",
    "Wish I was at the range instead of here. Make it quick.",
    "Defending freedoms or wasting time? Hopefully the former.",
    "Liberty and justice, sure. But let's not forget the right to bear arms.",
    "Less chit-chat, more action. Where are the swords?",
    "Bow at the ready. Try to make the debate worth my while.",
    "Fireball first, sword second. That's how I solve problems.",
  ],
};
